499:2make doc
 in dir /home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build (timeout 1200 secs)
 watching logfiles {}
 argv: make doc
 environment:
  HOME=/home/buildslave
  LOGNAME=buildslave
  MAIL=/var/mail/buildslave
  PATH=/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
  PWD=/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build
  SHELL=/bin/sh
  TERM=xterm
  USER=buildslave
 using PTY: False
,124:0rm -rf doc/build
rm -rf doc/source/generated
cd doc; \
	python make.py clean; \
	python make.py html
Running Sphinx v1.2b1
,920:1Exception occurred while building, starting debugger:
Traceback (most recent call last):
  File "/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/venv/lib/python2.7/site-packages/sphinx/cmdline.py", line 246, in main
    warningiserror, tags, verbosity, parallel)
  File "/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/venv/lib/python2.7/site-packages/sphinx/application.py", line 119, in __init__
    self.setup_extension(extension)
  File "/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/venv/lib/python2.7/site-packages/sphinx/application.py", line 282, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/doc/sphinxext/numpydoc.py", line 25, in <module>
    from .docscrape_sphinx import get_doc_object, SphinxDocString
ValueError: Attempted relative import in non-package
,179:0> /home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/doc/sphinxext/numpydoc.py(25)<module>()
-> from .docscrape_sphinx import get_doc_object, SphinxDocString
(Pdb) 
,57:2program finished with exit code 0
elapsedTime=10.098047
,