499:2make doc
 in dir /home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build (timeout 1200 secs)
 watching logfiles {}
 argv: make doc
 environment:
  HOME=/home/buildslave
  LOGNAME=buildslave
  MAIL=/var/mail/buildslave
  PATH=/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
  PWD=/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build
  SHELL=/bin/sh
  TERM=linux
  USER=buildslave
 using PTY: False
,124:0rm -rf doc/build
rm -rf doc/source/generated
cd doc; \
	python make.py clean; \
	python make.py html
Running Sphinx v1.1.3
,961:1Exception occurred while building, starting debugger:
Traceback (most recent call last):
  File "/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/venv/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 188, in main
    warningiserror, tags)
  File "/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/venv/local/lib/python2.7/site-packages/sphinx/application.py", line 102, in __init__
    confoverrides or {}, self.tags)
  File "/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/venv/local/lib/python2.7/site-packages/sphinx/config.py", line 216, in __init__
    exec code in config
  File "/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/doc/source/conf.py", line 74, in <module>
    import pandas
  File "/home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/pandas/__init__.py", line 6, in <module>
    from . import hashtable, tslib, lib
ImportError: cannot import name hashtable
,174:0cannot import name hashtable
> /home/buildslave/nd-bb-slave-sparc-sid/pandas-doc-builder/build/pandas/__init__.py(6)<module>()
-> from . import hashtable, tslib, lib
(Pdb) 
,56:2program finished with exit code 0
elapsedTime=3.342493
,