768:2xvfb-run --auto-servernum '--server-args=-screen 0 1024x768x24' nosetests --verbosity=3 --exe statsmodels
 in dir /home/buildslave/nd-bb-slave-sparc-wheezy/statsmodels-py2_x-wheezy-sparc/build/venv (timeout 1200 secs)
 watching logfiles {}
 argv: ['xvfb-run', '--auto-servernum', '--server-args=-screen 0 1024x768x24', 'nosetests', '--verbosity=3', '--exe', 'statsmodels']
 environment:
  HOME=/home/buildslave
  LOGNAME=buildslave
  MAIL=/var/mail/buildslave
  PATH=/home/buildslave/nd-bb-slave-sparc-wheezy/statsmodels-py2_x-wheezy-sparc/build/venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
  PWD=/home/buildslave/nd-bb-slave-sparc-wheezy/statsmodels-py2_x-wheezy-sparc/build/venv
  SHELL=/bin/sh
  TERM=xterm
  USER=buildslave
 using PTY: False
,10001:0nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
statsmodels.compatnp.tests.test_itercompat.test_zip_longest ... ok
statsmodels.compatnp.tests.test_itercompat.test_combinations ... ok
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
test_StepFunction (statsmodels.distributions.tests.test_ecdf.TestDistributions) ... ok
test_StepFunctionBadShape (statsmodels.distributions.tests.test_ecdf.TestDistributions) ... ok
test_StepFunctionRepeatedValues (statsmodels.distributions.tests.test_ecdf.TestDistributions) ... ok
test_StepFunctionValueSideRight (statsmodels.distributions.tests.test_ecdf.TestDistributions) ... ok
test_monotone_fn_inverter (statsmodels.distributions.tests.test_ecdf.TestDistributions) ... ok
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
statsmodels.graphics.tests.test_functional.test_banddepth_BD2 ... ok
statsmodels.graphics.tests.test_functional.test_banddepth_MBD ... ok
Test fboxplot and rainbowplot together, is much faster. ... ok
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
statsmodels.iolib.tests.test_pickle.test_pickle ... ok
Basic test, test_SimpleTable_1 ... ok
Test SimpleTable.extend_right() ... ok
Test SimpleTable.extend() as in extend down ... ok
Basic test, test_SimpleTable_4 ... ok
test_celldata (statsmodels.iolib.tests.test_table_econpy.test_Cell) ... ok
Limited test of custom custom labeling ... ok
Limited test of custom html_fmt ... ok
Limited test of custom ltx_fmt ... ok
Limited test of custom txt_fmt ... ok
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
statsmodels.sandbox.distributions.tests.test_extras.test_skewnorm ... ok
statsmodels.sandbox.distributions.tests.test_extras.test_skewt ... /usr/lib/python2.7/dist-packages/scipy/stats/distributions.py:4459: RuntimeWarning: overflow encountered in double_scalars
  Px /= sqrt(r*pi)*(1+(x**2)/r)**((r+1)/2)
ok
statsmodels.sandbox.distributions.tests.test_multivariate.TestMVDistributions.test_mvn_pdf ... ok
statsmodels.sandbox.distributions.tests.test_multivariate.TestMVDistributions.test_mvt_pdf ... ok
statsmodels.sandbox.distributions.tests.test_multivariate.Test_MVN_MVT_prob.test_mvn_mvt_1 ... ok
statsmodels.sandbox.distributions.tests.test_multivariate.Test_MVN_MVT_prob.test_mvn_mvt_2 ... ok
statsmodels.sandbox.distributions.tests.test_multivariate.Test_MVN_MVT_prob.test_mvn_mvt_3 ... ok
statsmodels.sandbox.distributions.tests.test_multivariate.Test_MVN_MVT_prob.test_mvn_mvt_4 ... ok
statsmodels.sandbox.distributions.tests.test_multivariate.Test_MVN_MVT_prob.test_mvn_mvt_5 ... ok
statsmodels.sandbox.distributions.tests.testtransf.Test_Transf2.test_equivalent ... ok
statsmodels.sandbox.distributions.tests.testtransf.Test_Transf2.test_equivalent_negsq ... ok
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
test_call (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_contrast1 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_contrast2 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_contrast3 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_contrast4 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_design (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_factor1 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_factor2 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_factor3 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_factor4 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_factor5 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_interactions (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_intercept1 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_intercept3 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_namespace (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_ordinal_factor (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_ordinal_factor2 (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_power (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_product (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_quantitative (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_str (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_subtract (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_termcolumns (statsmodels.sandbox.tests.test_formula.TestFormula) ... ok
test_add (statsmodels.sandbox.tests.test_formula.TestTerm) ... ok
test_init (statsmodels.sandbox.tests.test_formula.TestTerm) ... ok
test_mul (statsmodels.sandbox.tests.test_formula.TestTerm) ... ok
test_str (statsmodels.sandbox.tests.test_formula.TestTerm) ... ok
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
test_100_random_values (statsmodels.stats.libqsturng.tests.test_qsturng.test_psturng) ... ok
test_handful_to_known_values (statsmodels.stats.libqsturng.tests.test_qsturng.test_psturng) ... ok
test_invalid_parameters (statsmodels.stats.libqsturng.tests.test_qsturng.test_psturng) ... ok
scalar input -> scalar output ... ok
test_v_equal_one (statsmodels.stats.libqsturng.tests.test_qsturng.test_psturng) ... ok
vector input -> vector output ... ok
test_10000_to_ch (statsmodels.stats.libqsturng.tests.test_qsturng.test_qsturng) ... ok
test_handful_to_ch (statsmodels.stats.libqsturng.tests.test_qsturng.test_qsturng) ... ok
test_handful_to_tbl (statsmodels.stats.libqsturng.tests.test_qsturng.test_qsturng) ... ok
test_invalid_parameters (statsmodels.stats.libqsturng.tests.test_qsturng.test_qsturng) ... ok
scalar input -> scalar output ... ok
vector input -> vector output ... ok
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
statsmodels.stats.tests.test_moment_helpers.test_cov2corr ... ok
statsmodels.stats.tests.test_moment_helpers.test_moment_conversion ... ok
statsmodels.stats.tests.test_moment_helpers.test_moment_conversion_types ... ok
statsmodels.stats.tests.test_multi.test_multi_pvalcorrection ... ok
statsmodels.stats.tests.test_multi.test_hommel ... ok
statsmodels.stats.tests.test_multi.test_fdr_bky ... ok
statsmodels.stats.tests.test_multi.test_tukeyhsd ... ok
statsmodels.stats.tests.test_pairwise.TestTuckeyHSD2.test_group_tukey ... ok
statsmodels.stats.tests.test_pairwise.TestTuckeyHSD2.test_multicomptukey ... ok
statsmodels.stats.tests.test_pairwise.TestTuckeyHSD2.test_shortcut_function ... ok
statsmodels.stats.tests.test_pairwise.TestTuckeyHSD2s.test_group_tukey ... ok
statsmodels.stats.tests.test_pairwise.TestTuckeyHSD2s.test_multicomptukey ... ok
statsmodels.stats.tests.test_pairwise.TestTuckeyHSD2s.test_shortcut_function ... ok
statsmodels.stats.tests.test_pairwise.TestTuckeyHSD3.test_group_tukey ... ok
statsmodels.stats.tests.test_pairwise.TestTuckeyHSD3.test_multicomptukey ... ok
statsmodels.stats.tests.test_pairwise.TestTuckeyHSD3.test_shortcut_function ... ok
Failure: ImportError (No module named pandas) ... ERROR
statsmodels.stats.tests.test_qsturng.test_qstrung ... ok
Failure: ImportError (No module named pandas) ... ERROR
statsmodels.stats.tests.test_statstools.test_durbin_watson ... ok
statsmodels.stats.tests.test_statstools.test_omni_normtest ... ok
statsmodels.stats.tests.test_statstools.test_jarque_bera ... ok
statsmodels.stats.tests.test_statstools.test_shapiro ... ok
statsmodels.stats.tests.test_statstools.test_adnorm ... ok
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
statsmodels.tsa.interp.tests.test_denton.test_denton_quarterly ... ok
statsmodels.tsa.interp.tests.test_denton.test_denton_quarterly2 ... ok
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR
Failure: ImportError (No module named pandas) ... ERROR

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/base/tests/test_data.py", line 2, in <module>
    import pandas
Impor,10001:0tError: No module named pandas
-------------------- >> begin captured logging << --------------------
root: DEBUG: Enter SimpleTable.data2rows.
root: DEBUG: Exit SimpleTable.data2rows.
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/base/tests/test_shrink_pickle.py", line 11, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/discrete/tests/test_discrete.py", line 13, in <module>
    from statsmodels.discrete.discrete_model import *
  File "/usr/lib/pymodules/python2.7/statsmodels/discrete/discrete_model.py", line 24, in <module>
    import statsmodels.tools.tools as tools
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/genmod/tests/test_glm.py", line 8, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/graphics/tests/test_boxplots.py", line 5, in <module>
    from statsmodels.datasets import anes96
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/graphics/tests/test_factorplots.py", line 3, in <module>
    from pandas import Series
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/graphics/tests/test_gofplots.py", line 4, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

========================================,10001:0==============================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/graphics/tests/test_regressionplots.py", line 8, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/graphics/tests/test_tsaplots.py", line 4, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/iolib/tests/test_foreign.py", line 7, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/miscmodels/__init__.py", line 1, in <module>
    from tmodel import TLinearModel
  File "/usr/lib/pymodules/python2.7/statsmodels/miscmodels/tmodel.py", line 45, in <module>
    from statsmodels.base.model import GenericLikelihoodModel
  File "/usr/lib/pymodules/python2.7/statsmodels/base/model.py", line 3, in <module>
    from statsmodels.base.data import handle_data
  File "/usr/lib/pymodules/python2.7/statsmodels/base/data.py", line 7, in <module>
    from pandas import DataFrame, Series, TimeSeries
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/nonparametric/__init__.py", line 1, in <module>
    from kde import KDE
  File "/usr/lib/pymodules/python2.7/statsmodels/nonparametric/kde.py", line 17, in <module>
    from statsmodels.tools.decorators import (cache_readonly,
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/__init__.py", line 1, in <module>
    from linear_model import yule_walker
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/linear_model.py", line 37, in <module>
    from statsmodels.tools.tools import (add_constant, rank,
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/robust/__init__.py", line 5, in <module>
    from .scale import mad, stand_mad, Huber, HuberScale, hubers_scale
  File "/usr/lib/pymodules/python2.7/statsmodels/robust/scale.py", line 15, in <module>
    from statsmodels.tools import tools
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/pyth,10001:0on2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/sandbox/nonparametric/tests/test_smoothers.py", line 13, in <module>
    from statsmodels.regression.linear_model import OLS, WLS
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/__init__.py", line 1, in <module>
    from linear_model import yule_walker
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/linear_model.py", line 37, in <module>
    from statsmodels.tools.tools import (add_constant, rank,
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/sandbox/panel/tests/test_random_panel.py", line 14, in <module>
    import statsmodels.tools.eval_measures as em
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/sandbox/regression/test_numdiff.py", line 12, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/sandbox/tsa/__init__.py", line 51, in <module>
    from movstat import *
  File "/usr/lib/pymodules/python2.7/statsmodels/sandbox/tsa/movstat.py", line 51, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/sandbox/tests/test_gam.py", line 83, in <module>
    from statsmodels.sandbox.gam import AdditiveModel
  File "/usr/lib/pymodules/python2.7/statsmodels/sandbox/gam.py", line 53, in <module>
    from statsmodels.genmod.generalized_linear_model import GLM
  File "/usr/lib/pymodules/python2.7/statsmodels/genmod/generalized_linear_model.py", line 23, in <module>
    from statsmodels.tools.tools import rank
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/sandbox/tests/test_pca.py", line 14, in <module>
    from statsmodels.tsa.arima_process import arma_impulse_response
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/arima_process.py", line 58, in <module>
    from statsmodels.base.model import LikelihoodModel
  File "/usr/lib/pymodules/python2.7/statsmodels/base/model.py", line 3, in <module>
    from statsmodels.base.data import handle_data
  File "/usr/lib/pymodules/python2.7/statsmodels/base/data.py", line 7, in <module>
    from pandas import DataFrame, Series, TimeSeries
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/stats/tests/test_contrast.py", line 4, in <module>
    from statsmodels.stats.contrast import Contrast
  File "/usr/lib/pymodules/python2.7/statsmodels/stats/contrast.py", line 4, in <module>
    from statsmodels.tools.tools import clean0, rank, fullrank
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/stats/tests/test_diagnostic.py", li,10001:0ne 20, in <module>
    from statsmodels.regression.linear_model import OLS, GLSAR
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/__init__.py", line 1, in <module>
    from linear_model import yule_walker
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/linear_model.py", line 37, in <module>
    from statsmodels.tools.tools import (add_constant, rank,
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/stats/tests/test_groups_sw.py", line 12, in <module>
    import statsmodels.stats.sandwich_covariance as sw
  File "/usr/lib/pymodules/python2.7/statsmodels/stats/sandwich_covariance.py", line 107, in <module>
    from statsmodels.tools.grouputils import Group
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/stats/tests/test_panel_robustcov.py", line 13, in <module>
    from statsmodels.regression.linear_model import OLS
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/__init__.py", line 1, in <module>
    from linear_model import yule_walker
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/linear_model.py", line 37, in <module>
    from statsmodels.tools.tools import (add_constant, rank,
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/stats/tests/test_sandwich.py", line 15, in <module>
    from statsmodels.regression.linear_model import OLS, GLSAR
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/__init__.py", line 1, in <module>
    from linear_model import yule_walker
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/linear_model.py", line 37, in <module>
    from statsmodels.tools.tools import (add_constant, rank,
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/stats/tests/test_weightstats.py", line 14, in <module>
    from statsmodels.stats.weightstats import \
  File "/usr/lib/pymodules/python2.7/statsmodels/stats/weightstats.py", line 32, in <module>
    from statsmodels.tools.decorators import OneTimeProperty
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/base/tests/test_datetools.py", line 3, in <module>
    from statsmodels.tsa.base.datetools import (_date_from_idx,
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/base/datetools.py", line 3, in <module>
    from pandas import datetools as pandas_datetools
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/filters/tests/test_filters.py", line 3, in <module>
    from statsmodels.datasets import macrodata
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/kalmanf/__init__.py",,10001:0 line 1, in <module>
    from kalmanfilter import KalmanFilter
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/kalmanf/kalmanfilter.py", line 31, in <module>
    from statsmodels.tools.tools import chain_dot
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/vector_ar/tests/test_svar.py", line 5, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/vector_ar/tests/test_var.py", line 16, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/tests/test_adfuller_lag.py", line 10, in <module>
    import statsmodels.tsa.stattools as tsast
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/stattools.py", line 7, in <module>
    from statsmodels.regression.linear_model import OLS, yule_walker
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/__init__.py", line 1, in <module>
    from linear_model import yule_walker
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/linear_model.py", line 37, in <module>
    from statsmodels.tools.tools import (add_constant, rank,
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/tests/test_ar.py", line 4, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/tests/test_arima_process.py", line 7, in <module>
    from statsmodels.tsa.arima_process import (arma_impulse_response,
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/arima_process.py", line 58, in <module>
    from statsmodels.base.model import LikelihoodModel
  File "/usr/lib/pymodules/python2.7/statsmodels/base/model.py", line 3, in <module>
    from statsmodels.base.data import handle_data
  File "/usr/lib/pymodules/python2.7/statsmodels/base/data.py", line 7, in <module>
    from pandas import DataFrame, Series, TimeSeries
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/tests/test_arma.py", line 3, in <module>
    import statsmodels.sandbox.tsa.fftarma as fa
  File "/usr/lib/pymodules/python2.7/statsmodels/sandbox/tsa/__init__.py", line 51, in <module>
    from movstat import *
  File "/usr/lib/pymodules/python2.7/statsmodels/sandbox/tsa/movstat.py", line 51, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================,3232:0================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/tests/test_stattools.py", line 1, in <module>
    from statsmodels.tsa.stattools import (adfuller, acf, pacf_ols, pacf_yw,
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/stattools.py", line 7, in <module>
    from statsmodels.regression.linear_model import OLS, yule_walker
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/__init__.py", line 1, in <module>
    from linear_model import yule_walker
  File "/usr/lib/pymodules/python2.7/statsmodels/regression/linear_model.py", line 37, in <module>
    from statsmodels.tools.tools import (add_constant, rank,
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/pymodules/python2.7/statsmodels/tsa/tests/test_tsa_tools.py", line 7, in <module>
    import statsmodels.api as sm
  File "/usr/lib/pymodules/python2.7/statsmodels/api.py", line 1, in <module>
    import iolib, datasets, tools
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/__init__.py", line 5, in <module>
    import anes96, committee, ccard, copper, cpunish, elnino, grunfeld, longley, \
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/__init__.py", line 1, in <module>
    from data import *
  File "/usr/lib/pymodules/python2.7/statsmodels/datasets/anes96/data.py", line 87, in <module>
    import statsmodels.tools.datautils as du
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/__init__.py", line 1, in <module>
    from tools import add_constant, categorical
  File "/usr/lib/pymodules/python2.7/statsmodels/tools/tools.py", line 14, in <module>
    from pandas import DataFrame
ImportError: No module named pandas

----------------------------------------------------------------------
Ran 133 tests in 317.265s

FAILED (errors=39)
,58:2program finished with exit code 1
elapsedTime=342.183013
,